### ISSUE TITLE
ZSH won't run crontab commands

### ISSUE THREAD

**Issue by Rdbaker** [frostming/flask-crontab#2]
I've been trying to run this on my mac (which uses zsh) and couldn't debug why it wasn't working.

I found that using the `crontab -l` showed the command correctly:

```
* * * * * cd /Users/rdbaker/Development/Projects/prm && FLASK_APP=autoapp.py /Users/rdbaker/.virtualenvs/prm/bin/python -m flask crontab run 3f70df32a7224261e25a7921746479ac  # Flask cron jobs for prm
```

but it wouldn't run. I didn't take a look into the stdout/stderr of the process running the command, but I did try to copy/paste the command into my current shell and got an exit code 1 (without the command even running) and the message:

```
zsh: bad pattern: #
```

I can fix this locally by running `setopt interactive_comments` in my current shell, but that doesn't fix the issue for whatever process is running the command.

I can do work to fix this locally for myself, or we can fix it for all MacOS 10.15 users (who recently got auto-switched to zsh). 

I'll have a PR up shortly.

**Comment by frostming** [comment]
Looking forward to your PR.

**Comment by Rdbaker** [comment]
closing this- found out how to solve the issue, more details in #3
