### ISSUE TITLE
Can I use flask-crontab with flask blueprint?

### ISSUE THREAD

**Issue by lx1054331851** [frostming/flask-crontab#5]
Can I use flask-crontab with flask blueprint?

**Comment by frostming** [comment]
What do you mean by "with"?

Basically, flask-crontab has nothing to do with blueprints so they can work together.

**Comment by zozoens31** [comment]
Actually, I'm interested in this too; if I do the following:

`blueprint.py`
```python
app = flask.Blueprint('myBlueprint', __name__)
crontab = flask_crontab.Crontab(app)

# ... Use crontab here.
```

`server.py`
```python
from blueprint import app as my_blueprint

app = flask.Flask(__name__)
app.register_blueprint(my_blueprint)
```

Will the cron jobs be run?
